version: 2

jobs:
  build:
    docker:
      - image: "debian:buster"
    steps:
      - checkout
      - run:
          name: Install dependencies GCC
          command: 'apt-get update && apt-get install -y gcc make python3 python3-pip'
      - run:
          name: Install dependencies Python
          command: 'pip3 install -U pip && pip3 install -U setuptools && pip3 install -U norminette'
      - run:
          name: Build
          command: 'echo Building'
      - run:
          name: Unit-Test
          command: "echo Unit-Test"
      - run:
          name: Integration-Test
          command: "echo Integration-Test"
      - run:
          name: Norminette
          command: norminette srcs