version: 2

jobs:
  build:
    docker:
      - image: "debian:buster"
    steps:
      - checkout
      - run:
          name: Install dependenciesCLANG and Norminette
          command: 'apt-get update && apt-get -y install wget && apt-get install -y clang make python3 python3-pip && apt-get install -y libreadline-dev && pip3 install -U norminette'
      - run:
          name: Install Bash 3.2
          command: 'mkdir ~/bash && cd ~/bash && wget http://ftp.gnu.org/gnu/bash/bash-3.2.57.tar.gz && tar xvzf bash-3.2.57.tar.gz && cd bash-3.2.57 && ./configure && make && ./bash -version && cp bash /bin/bash'
      - run:
          name: Build
          command: 'echo Building'
      - run:
          name: Unit-Test
          command: "make test_run"
      - run:
          name: Unit-Test ASAN
          command: "make test_asan"
      - run:
          name: Acceptance-Test
          command: make acceptance_test
      - run:
          name: Norminette
          command: norminette src main.c