version: 2

jobs:
  build:
    docker:
      - image: "debian:buster"
    steps:
      - checkout
      - run:
          name: Install dependencies CLANG and Norminette
          command: 'apt-get update && apt-get -y install wget && apt-get install -y clang make python3 python3-pip && python3-pip install colorama && apt-get install -y libreadline-dev && pip3 install norminette==3.3.2'
      - run:
          name: Install Bash 3.2
          command: 'cp bash_dir/bash3.2 /bin/bash && bash --version | grep 3.2'
      - run:
          name: Build
          command: 'echo Building'
      - run:
          name: Unit-Test ASAN
          command: "make test_asan"
      - run:
          name: Unit-Test
          command: "make test_run"
      - run:
          name: Acceptance-Test ASAN
          command: make acceptance_test_asan
      - run:
          name: Acceptance-Test
          command: make acceptance_test
      - run:
          name: Norminette
          command: norminette libft src main.c